// Adziga — /app/admin/plans
// Sprint 13a — admin UI to view past multi-step plans.

import { prisma } from "@/lib/db";
import { requireRole } from "@/lib/session";
import { Role } from "@/lib/constants";
import { PageHeader } from "../../_components/page-header";
import { Card, Kpi, Badge } from "../../_components/ui";
import { fmtDateTime } from "@/lib/format";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function PlansPage() {
  await requireRole([Role.FOUNDER, Role.ADMIN]);
  const plans = await prisma.orchestrationPlan.findMany({
    where: {},
    orderBy: { createdAt: "desc" },
    take: 30
  });

  const completed = plans.filter((p) => p.status === "COMPLETED").length;
  const failed = plans.filter((p) => p.status === "FAILED").length;
  const running = plans.filter((p) => p.status === "RUNNING").length;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Multi-step plans"
        subtitle="Atomic marketing plans generated by the Strategy Agent. Each plan runs ROI → predict → anomalies → allocate → campaign.create in sequence."
        breadcrumbs={[{ label: "Admin", href: "/app/admin" }, { label: "Plans" }]}
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <Kpi label="Total" value={plans.length} />
        <Kpi label="Completed" value={completed} tone="success" />
        <Kpi label="Running" value={running} />
        <Kpi label="Failed" value={failed} tone={failed > 0 ? "accent" : "neutral"} />
      </div>

      <Card padding="none">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="text-xs text-ink-500 border-b border-ink-200 bg-ink-50">
              <tr>
                <th className="text-left px-4 py-2">When</th>
                <th className="text-left px-4 py-2">Status</th>
                <th className="text-left px-4 py-2">Prompt</th>
                <th className="text-left px-4 py-2">Completed</th>
              </tr>
            </thead>
            <tbody>
              {plans.map((p) => (
                <tr key={p.id} className="border-b border-ink-100">
                  <td className="px-4 py-2 text-xs">{fmtDateTime(p.createdAt)}</td>
                  <td className="px-4 py-2 text-xs">
                    <Badge variant={statusVariant(p.status)}>{p.status}</Badge>
                  </td>
                  <td className="px-4 py-2 text-xs text-ink-700 max-w-md truncate" title={p.strategy}>
                    {p.strategy}
                  </td>
                  <td className="px-4 py-2 text-xs text-ink-500">
                    {p.completedAt ? fmtDateTime(p.completedAt) : "—"}
                  </td>
                </tr>
              ))}
              {plans.length === 0 && (
                <tr>
                  <td colSpan={4} className="text-center text-ink-500 py-12">
                    No plans yet. The Strategy Agent will create one when it plans a multi-channel campaign.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}

function statusVariant(s: string): "neutral" | "brand" | "success" | "warning" | "accent" {
  if (s === "COMPLETED") return "success";
  if (s === "RUNNING") return "brand";
  if (s === "FAILED") return "warning";
  return "neutral";
}
